# LeNet
Mnist 데이터 셋을 이용하여 훈련한 뒤 손글씨 데이터로 성능 검증

라이브러리 import

In [ ]:
clear

In [ ]:
# 구글 드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
from tensorflow import keras
import numpy as np

# 모델
from tensorflow.keras.models import model_from_json
from tensorflow.keras.optimizers import SGD

# 이미지처리
import cv2
from google.colab.patches import cv2_imshow
from skimage.transform import resize
#from imageio import imread

Mounted at /content/drive


훈련된 모델 불러옴

In [ ]:
# 모델 로드
model_architecture = '/content/drive/MyDrive/model/CNN_LeNet_architecture.json'
model_weights = '/content/drive/MyDrive/model/CNN_LeNet_weights.h5'
model = model_from_json(open(model_architecture).read())
model.load_weights(model_weights)

# 훈련
model.compile(loss = "categorical_crossentropy", optimizer = tf.keras.optimizers.Adam(), metrics = ["accuracy"])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 24, 24, 20)        520       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 12, 12, 20)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 8, 8, 50)          25050     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 4, 4, 50)         0         
 2D)                                                             
                                                                 
 flatten (Flatten)           (None, 800)               0         
                                                                 
 dense (Dense)               (None, 500)               4

test data 불러오기

In [ ]:
# 이미지 로드
img_names = ['/content/drive/MyDrive/dataset/Mnist/number0_1.jpg',
             '/content/drive/MyDrive/dataset/Mnist/number1_1.jpg',
             '/content/drive/MyDrive/dataset/Mnist/number2_1.jpg',
             '/content/drive/MyDrive/dataset/Mnist/number3_1.jpg',
             '/content/drive/MyDrive/dataset/Mnist/number4_1.jpg',
             '/content/drive/MyDrive/dataset/Mnist/number5_1.jpg',
             '/content/drive/MyDrive/dataset/Mnist/number6_1.jpg',
             '/content/drive/MyDrive/dataset/Mnist/number7_1.jpg',
             '/content/drive/MyDrive/dataset/Mnist/number8_1.jpg',
             '/content/drive/MyDrive/dataset/Mnist/number9_1.jpg',
             '/content/drive/MyDrive/dataset/Mnist/number0_2.jpg',
             '/content/drive/MyDrive/dataset/Mnist/number1_2.jpg',
             '/content/drive/MyDrive/dataset/Mnist/number2_2.jpg',
             '/content/drive/MyDrive/dataset/Mnist/number3_2.jpg',
             '/content/drive/MyDrive/dataset/Mnist/number4_2.jpg',
             '/content/drive/MyDrive/dataset/Mnist/number5_2.jpg',
             '/content/drive/MyDrive/dataset/Mnist/number6_2.jpg',
             '/content/drive/MyDrive/dataset/Mnist/number7_2.jpg',
             '/content/drive/MyDrive/dataset/Mnist/number8_2.jpg',
             '/content/drive/MyDrive/dataset/Mnist/number9_2.jpg']

# img = cv2.imread(img_name, 0) # cv2.imread(img, flag) flag 0: 흑백으로 읽음
imgs = np.array([cv2.imread(img_name, 0) for img_name in img_names])

for i in range(len(img_names)):
  cv2_imshow(imgs[i])

print("imgs type:", type(imgs))
imgs = imgs.reshape((20, 28, 28, 1))

print("imgs.shape:", imgs.shape)
print("imgs[0].shape:", imgs[0].shape)

# 정규화
imgs = imgs / 255.0

# 형식 변환
imgs = imgs.astype('float32')

imgs type: <class 'numpy.ndarray'>
imgs.shape: (20, 28, 28, 1)
imgs[0].shape: (28, 28, 1)


test

In [ ]:
prediction = model.predict(imgs) 
classes = np.argmax(prediction, axis=1)

#print("predictions:", np.argmax(prediction))
print("classes:", classes)
answer = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("answer: ", answer)

1/1 [==============================] - 0s 430ms/step
classes: [0 1 2 5 4 5 5 8 8 1 9 1 2 3 4 5 0 7 4 1]
answer:  [0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]


In [ ]:
result = (np.count_nonzero(classes - answer))/20
print(1-result)

0.6


Mnist dataset으로 테스트해봄

In [ ]:
from tensorflow.keras import datasets, layers, models, optimizers
import tensorflow as tf

(X_train, Y_train), (X_test, Y_test) = datasets.mnist.load_data()

# 크기 조정
X_train = X_train.reshape((60000, 28, 28, 1))
X_test = X_test.reshape((10000, 28, 28, 1))

# 정규화
X_train, X_test = X_train / 255.0, X_test / 255.0

# 형식 변환
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

Y_train = tf.keras.utils.to_categorical(Y_train, 10)
Y_test = tf.keras.utils.to_categorical(Y_test, 10)

score = model.evaluate(X_test, Y_test)
print("\nTest score:", score[0])
print('Test accuracy:', score[1])

313/313 [==============================] - 4s 11ms/step - loss: 0.1387 - accuracy: 0.9577

Test score: 0.13872498273849487
Test accuracy: 0.9577000141143799


In [ ]:
prediction = model.predict(X_test[0:10]) 
classes = np.argmax(prediction, axis=1)

#print("predictions:", np.argmax(prediction))
print("classes:", classes)

print("answer: [7 2 1 0 4 1 4 9 5 9]")
print(Y_test[0:10])
print(X_test[0:10].shape)

1/1 [==============================] - 0s 23ms/step
classes: [7 2 1 0 4 1 4 9 5 9]
answer: [7 2 1 0 4 1 4 9 5 9]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
(10, 28, 28, 1)
